name: Scheduled Task
on:
  schedule:
    - cron: '*/5 15-15 * * 1-5'  # Every 5 minutes, 9:00 AM - 10:00 AM CST, weekdays
    - cron: '0 16-22 * * 1-5'  # Every hour, except 9:00 AM - 10:00 AM CST, weekdays
jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Flask App
        run: |
          curl https://stonksbyedk.onrender.com